[pytest]
markers =
    regression: marks tests as regression tests
    smoke: marks tests as smoke tests
    auth: marks tests related to authorization
    cart: marks tests related to shopping cart
    checkout: marks tests related to checkout process
    inventory: marks tests related to product inventory
addopts = -v --tb=short
